In [1]:
import os
os.chdir('C:/Users/hu612/Desktop/School/수DA쟁이/Project/개인과제/data')

In [2]:
import pandas as pd
import numpy as np

train=pd.read_csv('train_features.csv')
train_labels=pd.read_csv('train_labels.csv')
test=pd.read_csv('test_features.csv')
submission=pd.read_csv('sample_submission.csv')

In [11]:
import tensorflow as tf
X_train = train[(train['id']>= 0) & (train['id']<=2499)]
X_test = train[train['id'] >= 2500]
X_train = tf.reshape(np.array(X_train.iloc[:,2:]),[-1, 600, 6])
X_test = tf.reshape(np.array(X_test.iloc[:,2:]),[-1, 600, 6])

from tensorflow.keras.utils import to_categorical
y =  train_labels['label']
slice_arr = slice(0,2500,1)
y_train = y[slice_arr]

slice_arr2 = slice(2500,3125,1)
y_test = y[slice_arr2]

y_train_encoding = tf.keras.utils.to_categorical(y_train)
y_test_encoding = tf.keras.utils.to_categorical(y_test)

In [12]:
X_train = X_train.numpy()

In [13]:
X_train = X_train.reshape((2500,-1))

In [14]:
X_test = X_test.numpy()

In [15]:
X_test = X_test.reshape((625,-1))

In [16]:
print(X_train.shape, y_train_encoding.shape)
print(X_test.shape, y_test_encoding.shape)

(2500, 3600) (2500, 61)
(625, 3600) (625, 61)


In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [18]:
knn.fit(X_train, y_train_encoding)

KNeighborsClassifier(n_neighbors=3)

In [19]:
prediction = knn.predict(X_test)

In [20]:
 print("테스트 세트에 대한 예측값:\n {}".format(prediction))

테스트 세트에 대한 예측값:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [30]:
prediction

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [31]:
y_test_encoding

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [27]:
print("테스트 세트의 정확도: {:.2f}".format(knn.score(X_test, y_test_encoding)))

테스트 세트의 정확도: 0.12


# 이거 엄청 안좋게 나올거 같은데 ㅎㅎ ,,

In [32]:
test_X=tf.reshape(np.array(test.iloc[:,2:]),[-1, 600, 6])
test_X.shape
test_X = test_X.numpy()
test_X = test_X.reshape((782,-1))

In [33]:
test_X.shape

(782, 3600)

In [34]:
prediction=knn.predict(test_X)

In [35]:
submission.iloc[:,1:]=prediction

In [36]:
submission.to_csv('C:/Users/hu612/Desktop/School/수DA쟁이/Project/개인과제/data/KNN/KNN1.csv', index=False)

# knn: 12.8512